PRODUCT_VERSION_MAJOR = 5
PRODUCT_VERSION_MINOR = 0
GENESIS_VERSION_TAG := Yume

CURRENT_DEVICE=$(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)

GENESIS_BUILD_DATE := $(shell date -u +%Y%m%d)

GENESIS_BUILDTYPE ?= UNOFFICIAL

GENESIS_VERSION := GenesisOS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(GENESIS_BUILD_DATE)-$(GENESIS_BUILDTYPE)-$(CURRENT_DEVICE)-$(GENESIS_VERSION_TAG)

# Display version
GENESIS_DISPLAY_VERSION := $(GENESIS_VERSION_TAG)-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# GenesisOS version properties
PRODUCT_PRODUCT_PROPERTIES += \
    ro.genesis.version=$(GENESIS_VERSION) \
    ro.genesis.device=$(GENESIS_BUILD) \
    ro.genesis.maintainer=$(GENESIS_MAINTAINER) \
    ro.genesis.display.version=$(GENESIS_DISPLAY_VERSION) \
    ro.genesis.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.genesis.releasetype=$(GENESIS_BUILDTYPE)
